### ISSUE TITLE
Quote the Libraries 

### ISSUE THREAD

**Issue by chemickypes** [ravindrabarthwal/GramBoxApp#1]
Hi, I hope you'll quote the libraries used within your app.
As you say in your Open Source License file 

> Grambox is only made possible because of the hard work of the community member

I'd like that my hard work will be quoted.
I'm the owner of glithy library that you used in Grambox and my code is licensed, so I'd like to read [Glitchy ](https://github.com/chemickypes/Glitchy) app name.

**Comment by ravindrabarthwal** [comment]
Firstly, I want to apologise for not being efficient enough to complete
that page because of personal schedule.
I'll promise by next Monday each and every library will be listed there.
Regards

**Comment by ravindrabarthwal** [comment]
@chemickypes I have added license and link to your github repo. It will take me further time for adding all the license.

**Comment by chemickypes** [comment]
ok thanks! Grambox: great idea! ;)
